# [\#6666 PR](https://github.com/ethereum/solidity/pull/6666) `merged`: Group function definitions
**Labels**: `external contribution :star:`


#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) opened issue at [2019-05-06 07:51](https://github.com/ethereum/solidity/pull/6666):

Fixes #5405 

<!--### Your checklist for this pull request

Please review the [guidelines for contributing](http://solidity.readthedocs.io/en/latest/contributing.html) to this repository.

Please also note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.
-->

### Description

<!--
Please explain the changes you made here.

Thank you for your help!
-->

### Checklist
- [x] Code compiles correctly
- [x] All tests are passing
- [x] New tests have been created which fail without the change (if possible)
- [x] README / documentation was extended, if necessary
- [x] Changelog entry (if change is visible to the user)
- [x] Used meaningful commit messages


#### <img src="https://avatars.githubusercontent.com/u/44874361?v=4" width="50">[stackenbotten](https://github.com/stackenbotten) commented at [2019-05-06 07:51](https://github.com/ethereum/solidity/pull/6666#issuecomment-489535852):

There was an error when running `test_check_style` for commit `4154f8cc043a71e73f8a8f5b85a8504377758310`:
```
Coding style error:
 libyul/backends/evm/EVMCodeTransform.cpp:834: const FunctionDefinition *seriesStart;
 libyul/backends/evm/EVMCodeTransform.cpp:837: const FunctionDefinition *functionDefinition = boost::get<FunctionDefinition>(&statement);

```
Please check that your changes are working as intended.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2019-05-16 10:26](https://github.com/ethereum/solidity/pull/6666#issuecomment-493011747):

@vedant1811 do you still want to continue on this? Do you need some help? Please don't hesitate to ask in https://gitter.im/ethereum/solidity-dev

#### <img src="https://avatars.githubusercontent.com/u/44874361?v=4" width="50">[stackenbotten](https://github.com/stackenbotten) commented at [2019-05-16 13:51](https://github.com/ethereum/solidity/pull/6666#issuecomment-493076131):

There was an error when running `test_check_style` for commit `156435ee9e0f1a214afceb56c85b953478da5fec`:
```
Error: Trailing whitespace found:
 libyul/backends/evm/EVMCodeTransform.cpp:887: 

```
Please check that your changes are working as intended.

#### <img src="https://avatars.githubusercontent.com/in/254?v=4" width="50">[codecov](https://github.com/apps/codecov) commented at [2019-05-25 10:55](https://github.com/ethereum/solidity/pull/6666#issuecomment-495908217):

# [Codecov](https://codecov.io/gh/ethereum/solidity/pull/6666?src=pr&el=h1) Report
> Merging [#6666](https://codecov.io/gh/ethereum/solidity/pull/6666?src=pr&el=desc) into [develop](https://codecov.io/gh/ethereum/solidity/commit/56db792ad99cf0fe28053685b202218c76f5745c?src=pr&el=desc) will **increase** coverage by `0.06%`.
> The diff coverage is `100%`.

[![Impacted file tree graph](https://codecov.io/gh/ethereum/solidity/pull/6666/graphs/tree.svg?width=650&token=87PGzVEwU0&height=150&src=pr)](https://codecov.io/gh/ethereum/solidity/pull/6666?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##           develop    #6666      +/-   ##
===========================================
+ Coverage    86.85%   86.91%   +0.06%     
===========================================
  Files          431      429       -2     
  Lines        41056    41022      -34     
  Branches      4841     4835       -6     
===========================================
- Hits         35658    35655       -3     
+ Misses        3798     3776      -22     
+ Partials      1600     1591       -9
```

| Flag | Coverage Δ | |
|---|---|---|
| #all | `86.91% <100%> (+0.06%)` | :arrow_up: |
| #syntax | `25.32% <0%> (+0.01%)` | :arrow_up: |

#### <img src="https://avatars.githubusercontent.com/u/44874361?v=4" width="50">[stackenbotten](https://github.com/stackenbotten) commented at [2019-05-25 10:55](https://github.com/ethereum/solidity/pull/6666#issuecomment-495908226):

There was an error when running `test_check_style` for commit `3e604e402616ed2d6cf329ec1a1518808b457038`:
```
Coding style error:
 libyul/backends/evm/EVMCodeTransform.cpp:727: const AbstractAssembly::LabelID* seriesStart = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:731: const FunctionDefinition* functionDefinition = boost::get<FunctionDefinition>(&statement);
 libyul/backends/evm/EVMCodeTransform.cpp:736: const AbstractAssembly::LabelID labelId = m_assembly.newLabelId();

```
Please check that your changes are working as intended.

#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) commented at [2019-05-26 04:53](https://github.com/ethereum/solidity/pull/6666#issuecomment-495969142):

The custom test case generated the following expected output:

```
Pretty printed source:
object "Contract" {
    code {
        {
            function f()
            {
            }
            function g()
            {
            }
            sstore(0, 1)
        }
    }
}


Binary representation:
600f566008565b565b600e565b565b5b6001600055

Text representation:
  jump(tag_1)
    /* "test.yul":41:56   */
  jump(tag_2)
tag_3:
    /* "test.yul":54:56   */
  jump
tag_2:
    /* "test.yul":57:72   */
  jump(tag_4)
tag_5:
    /* "test.yul":70:72   */
  jump
tag_4:
tag_1:
    /* "test.yul":83:84   */
  0x01
    /* "test.yul":80:81   */
  0x00
    /* "test.yul":73:85   */
  sstore
```

I need to fix 1 test failure, and add tests for the above optimisation

#### <img src="https://avatars.githubusercontent.com/u/44874361?v=4" width="50">[stackenbotten](https://github.com/stackenbotten) commented at [2019-05-26 07:46](https://github.com/ethereum/solidity/pull/6666#issuecomment-495977605):

There was an error when running `test_check_style` for commit `6965b7ffaeacfdc08feb1c9abb0f03f88a76df71`:
```
Coding style error:
 libyul/backends/evm/EVMCodeTransform.cpp:729: const AbstractAssembly::LabelID* seriesLabel = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:730: const Statement* seriesEnd = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:850:const std::unordered_map<Statement const*, Statement const*> CodeTransform::groupFunctionDefinitions(vector<Statement> const& _statements) const
 libyul/backends/evm/EVMCodeTransform.cpp:854: const Statement* seriesStart = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:855: const Statement* lastFd = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:859: const FunctionDefinition* functionDefinition = boost::get<FunctionDefinition>(&statement);
 libyul/backends/evm/EVMCodeTransform.h:226: const std::unordered_map<Statement const*, Statement const*> groupFunctionDefinitions(std::vector<Statement> const& _statements) const;

```
Please check that your changes are working as intended.

#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) commented at [2019-05-26 09:20](https://github.com/ethereum/solidity/pull/6666#issuecomment-495983158):

> There was an error when running `test_check_style` for commit `6965b7ffaeacfdc08feb1c9abb0f03f88a76df71`:
> 
> ```
> Coding style error:
>  libyul/backends/evm/EVMCodeTransform.cpp:729: const AbstractAssembly::LabelID* seriesLabel = nullptr;
>  libyul/backends/evm/EVMCodeTransform.cpp:730: const Statement* seriesEnd = nullptr;
>  libyul/backends/evm/EVMCodeTransform.cpp:850:const std::unordered_map<Statement const*, Statement const*> CodeTransform::groupFunctionDefinitions(vector<Statement> const& _statements) const
>  libyul/backends/evm/EVMCodeTransform.cpp:854: const Statement* seriesStart = nullptr;
>  libyul/backends/evm/EVMCodeTransform.cpp:855: const Statement* lastFd = nullptr;
>  libyul/backends/evm/EVMCodeTransform.cpp:859: const FunctionDefinition* functionDefinition = boost::get<FunctionDefinition>(&statement);
>  libyul/backends/evm/EVMCodeTransform.h:226: const std::unordered_map<Statement const*, Statement const*> groupFunctionDefinitions(std::vector<Statement> const& _statements) const;
> ```
> 
> Please check that your changes are working as intended.

Error statements are not very helpful. I am guessing I shouldn't be writing ` = nullptr;` in variable definitions but I'm not sure what's wrong with `const FunctionDefinition* functionDefinition = boost::get<FunctionDefinition>(&statement);`

#### <img src="https://avatars.githubusercontent.com/u/44874361?v=4" width="50">[stackenbotten](https://github.com/stackenbotten) commented at [2019-05-26 09:52](https://github.com/ethereum/solidity/pull/6666#issuecomment-495984992):

There was an error when running `test_check_style` for commit `a4cae840fbd201e2e7826183a06d787076fcee22`:
```
Coding style error:
 libyul/backends/evm/EVMCodeTransform.cpp:729: const AbstractAssembly::LabelID* seriesLabel = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:730: const Statement* seriesEnd = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:850:const std::unordered_map<Statement const*, Statement const*> CodeTransform::groupFunctionDefinitions(vector<Statement> const& _statements) const
 libyul/backends/evm/EVMCodeTransform.cpp:854: const Statement* seriesStart = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:855: const Statement* lastFd = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:859: const FunctionDefinition* functionDefinition = boost::get<FunctionDefinition>(&statement);
 libyul/backends/evm/EVMCodeTransform.h:226: const std::unordered_map<Statement const*, Statement const*> groupFunctionDefinitions(std::vector<Statement> const& _statements) const;

```
Please check that your changes are working as intended.

#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) commented at [2019-05-27 07:23](https://github.com/ethereum/solidity/pull/6666#issuecomment-496107970):

I have no idea what's failing here: https://circleci.com/gh/ethereum/solidity/130187?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link :(

#### <img src="https://avatars.githubusercontent.com/u/44874361?v=4" width="50">[stackenbotten](https://github.com/stackenbotten) commented at [2019-05-28 03:57](https://github.com/ethereum/solidity/pull/6666#issuecomment-496356324):

There was an error when running `test_check_style` for commit `d30dab020e5184d9fae4349eeb83d9451580c9ff`:
```
Coding style error:
 libyul/backends/evm/EVMCodeTransform.cpp:730: const Statement* seriesEnd = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:849:const std::unordered_map<Statement const*, Statement const*> CodeTransform::groupFunctionDefinitions(vector<Statement> const& _statements) const
 libyul/backends/evm/EVMCodeTransform.cpp:853: const Statement* seriesStart = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:854: const Statement* lastFd = nullptr;
 libyul/backends/evm/EVMCodeTransform.cpp:858: const FunctionDefinition* functionDefinition = boost::get<FunctionDefinition>(&statement);
 libyul/backends/evm/EVMCodeTransform.h:226: const std::unordered_map<Statement const*, Statement const*> groupFunctionDefinitions(std::vector<Statement> const& _statements) const;

```
Please check that your changes are working as intended.

#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) commented at [2019-06-12 09:02](https://github.com/ethereum/solidity/pull/6666#issuecomment-501185319):

@chriseth I'm free from my last job, so I can try to overlap 1-2 hours of work with your timings.

This PR is >1 month old; I want to finish it ASAP :)

#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) commented at [2019-06-13 17:24](https://github.com/ethereum/solidity/pull/6666#issuecomment-501800187):

I am still getting `Stack height mismatch between analysis and code generation phase` in 2 test cases.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2019-06-14 10:59](https://github.com/ethereum/solidity/pull/6666#issuecomment-502065953):

Note: the failures is for EVM 1.5 cases.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2019-06-17 15:41](https://github.com/ethereum/solidity/pull/6666#issuecomment-502737537):

Looks good! Please rebase and squash into a single commit and add a changelog entry.

#### <img src="https://avatars.githubusercontent.com/u/3260363?u=801d9204e5d0deb6af511e7f320de6d09eae60dd&v=4" width="50">[vedant1811](https://github.com/vedant1811) commented at [2019-06-18 16:41](https://github.com/ethereum/solidity/pull/6666#issuecomment-503216319):

@chriseth, @ekpyron Looks like the relevant CI tests have passed and we can merge this PR.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
